import { pgTable, text, serial, integer, boolean, timestamp, jsonb, doublePrecision, varchar, index, numeric, date, uniqueIndex } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";
import { relations, sql } from "drizzle-orm";

// === SESSION TABLE (kept for express-session) ===
export const sessions = pgTable(
  "sessions",
  {
    sid: varchar("sid").primaryKey(),
    sess: jsonb("sess").notNull(),
    expire: timestamp("expire").notNull(),
  },
  (table) => [index("IDX_session_expire").on(table.expire)]
);

// === EMPLOYEES TABLE (replaces users + beauticians) ===
export const employees = pgTable("employees", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  mobile: text("mobile").unique(),
  username: text("username").unique(),
  email: text("email").unique(),
  passwordHash: text("password_hash").notNull(),
  role: text("role").notNull().default("employee"), // 'employee' | 'admin'
  isOnline: boolean("is_online").default(false),
  currentLatitude: doublePrecision("current_latitude"),
  currentLongitude: doublePrecision("current_longitude"),
  lastActiveTime: timestamp("last_active_time"),
  createdAt: timestamp("created_at").defaultNow(),
});

// === ORDERS TABLE ===
export const orders = pgTable("orders", {
  id: serial("id").primaryKey(),
  customerName: text("customer_name").notNull(),
  phone: text("phone").notNull(),
  address: text("address").notNull(),
  mapsUrl: text("maps_url"),
  latitude: doublePrecision("latitude"),
  longitude: doublePrecision("longitude"),
  services: jsonb("services").notNull().$type<{ name: string; price: number }[]>(),
  amount: integer("amount").notNull(),
  duration: integer("duration").notNull().default(60),
  appointmentTime: timestamp("appointment_time").notNull(),
  paymentMode: text("payment_mode").notNull().default("cash"),
  status: text("status").notNull().default("pending"),
  employeeId: integer("employee_id").references(() => employees.id),
  hasIssue: boolean("has_issue").default(false),
  sheetRowId: text("sheet_row_id"),
  sheetDate: text("sheet_date"),
  sheetTime: text("sheet_time"),
  orderNum: integer("order_num"),
  externalOrderId: text("external_order_id"),
  areaName: text("area_name"),
  beauticianHomeArea: text("beautician_home_area"),
  orderAreaName: text("order_area_name"),
  acceptanceStatus: text("acceptance_status").default("pending"),
  // Set to true when admin manually reassigns — prevents sheet sync from overriding
  manuallyAssigned: boolean("manually_assigned").default(false),
}, (table) => [
  index("idx_orders_appointment_time").on(table.appointmentTime),
  index("idx_orders_employee").on(table.employeeId),
  uniqueIndex("idx_orders_external_order_id_unique").on(table.externalOrderId),
]);

// === INVENTORY ===
export const products = pgTable("products", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(),
  unit: text("unit").notNull(),
  costPerUnit: numeric("cost_per_unit").notNull(),
  lowStockThreshold: numeric("low_stock_threshold").notNull().default("0"),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").defaultNow(),
}, (table) => [
  index("idx_products_name").on(table.name),
]);

export const productPurchases = pgTable("product_purchases", {
  id: serial("id").primaryKey(),
  productId: integer("product_id").notNull().references(() => products.id),
  quantity: numeric("quantity").notNull(),
  purchaseDate: date("purchase_date").notNull(),
  vendorName: text("vendor_name"),
  invoiceNumber: text("invoice_number"),
  createdBy: integer("created_by").references(() => employees.id),
  createdAt: timestamp("created_at").defaultNow(),
}, (table) => [
  index("idx_product_purchases_product").on(table.productId),
  index("idx_product_purchases_date").on(table.purchaseDate),
]);

export const productConsumptions = pgTable("product_consumptions", {
  id: serial("id").primaryKey(),
  orderId: integer("order_id").notNull().references(() => orders.id),
  beauticianId: integer("beautician_id").notNull().references(() => employees.id),
  productId: integer("product_id").notNull().references(() => products.id),
  quantityUsed: numeric("quantity_used").notNull(),
  autoGenerated: boolean("auto_generated").notNull().default(true),
  createdAt: timestamp("created_at").defaultNow(),
  usedAt: timestamp("used_at").defaultNow(),
}, (table) => [
  index("idx_product_consumptions_order").on(table.orderId),
  index("idx_product_consumptions_beautician").on(table.beauticianId),
  index("idx_product_consumptions_product").on(table.productId),
  uniqueIndex("idx_product_consumptions_order_product_unique").on(table.orderId, table.productId),
]);

export const productRequests = pgTable("product_requests", {
  id: serial("id").primaryKey(),
  beauticianId: integer("beautician_id").notNull().references(() => employees.id),
  productId: integer("product_id").notNull().references(() => products.id),
  quantityRequested: numeric("quantity_requested").notNull(),
  quantityApproved: numeric("quantity_approved"),
  status: text("status").notNull().default("pending"),
  reason: text("reason"),
  createdAt: timestamp("created_at").defaultNow(),
  requestedAt: timestamp("requested_at").defaultNow(),
  approvedAt: timestamp("approved_at"),
  approvedBy: integer("approved_by").references(() => employees.id),
}, (table) => [
  index("idx_product_requests_beautician").on(table.beauticianId),
  index("idx_product_requests_status").on(table.status),
]);

export const serviceProductMapping = pgTable("service_product_mapping", {
  id: serial("id").primaryKey(),
  serviceName: text("service_name").notNull(),
  productId: integer("product_id").notNull().references(() => products.id),
  quantityRequired: numeric("quantity_required").notNull(),
}, (table) => [
  index("idx_service_product_mapping_service").on(table.serviceName),
  index("idx_service_product_mapping_product").on(table.productId),
  uniqueIndex("idx_service_product_mapping_service_product_unique").on(table.serviceName, table.productId),
]);

export const productsNotFound = pgTable("products_not_found", {
  id: serial("id").primaryKey(),
  orderId: integer("order_id"),
  externalOrderId: text("external_order_id"),
  serviceName: text("service_name").notNull(),
  productName: text("product_name"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const orderDefaultProducts = pgTable("order_default_products", {
  id: serial("id").primaryKey(),
  productId: integer("product_id").notNull().references(() => products.id),
  quantity: numeric("quantity").notNull(),
}, (table) => [
  uniqueIndex("idx_order_default_products_product_unique").on(table.productId),
]);

// === ISSUES TABLE ===
export const issues = pgTable("issues", {
  id: serial("id").primaryKey(),
  orderId: integer("order_id").references(() => orders.id),
  employeeId: integer("employee_id").references(() => employees.id),
  issueType: text("issue_type").notNull(),
  notes: text("notes"),
  latitude: doublePrecision("latitude"),
  longitude: doublePrecision("longitude"),
  status: text("status").notNull().default("open"), // 'open' | 'resolved'
  createdAt: timestamp("created_at").defaultNow(),
});

// === ATTENDANCE TABLE ===
export const attendance = pgTable("attendance", {
  id: serial("id").primaryKey(),
  employeeId: integer("employee_id").references(() => employees.id),
  shiftStart: timestamp("shift_start"),
  shiftEnd: timestamp("shift_end"),
  status: text("status").notNull().default("active"), // 'active' | 'ended'
});

// === LOCATION HISTORY ===
export const locationHistory = pgTable("location_history", {
  id: serial("id").primaryKey(),
  employeeId: integer("employee_id").references(() => employees.id),
  latitude: doublePrecision("latitude").notNull(),
  longitude: doublePrecision("longitude").notNull(),
  timestamp: timestamp("timestamp").defaultNow(),
});

// === BEAUTICIAN LIVE TRACKING ===
export const beauticianLiveTracking = pgTable("beautician_live_tracking", {
  id: serial("id").primaryKey(),
  beauticianId: integer("beautician_id").notNull().references(() => employees.id),
  orderId: integer("order_id").references(() => orders.id),
  latitude: doublePrecision("latitude").notNull(),
  longitude: doublePrecision("longitude").notNull(),
  accuracy: doublePrecision("accuracy"),
  speed: doublePrecision("speed"),
  status: text("status").notNull().default("idle"), // 'traveling' | 'at_location' | 'idle'
  timestamp: timestamp("timestamp").defaultNow(),
}, (table) => [
  index("idx_live_tracking_beautician").on(table.beauticianId),
  index("idx_live_tracking_order").on(table.orderId),
  index("idx_live_tracking_timestamp").on(table.timestamp),
]);

// === ORDER SERVICE SESSIONS ===
export const orderServiceSessions = pgTable("order_service_sessions", {
  id: serial("id").primaryKey(),
  orderId: integer("order_id").notNull().references(() => orders.id),
  beauticianId: integer("beautician_id").notNull().references(() => employees.id),
  serviceStartTime: timestamp("service_start_time").notNull().defaultNow(),
  expectedDurationMinutes: integer("expected_duration_minutes").notNull().default(60),
  serviceEndTime: timestamp("service_end_time"),
  status: text("status").notNull().default("active"), // 'active' | 'completed' | 'cancelled'
}, (table) => [
  index("idx_service_session_order").on(table.orderId),
  index("idx_service_session_beautician").on(table.beauticianId),
]);

// === ATTENDANCE RECORDS ===
// status: 'present' | 'absent' | 'week_off' | 'half_day'
// week_off is only valid Mon-Thu. Fri-Sun can only be present/absent/half_day.
export const attendanceRecords = pgTable("attendance_records", {
  id: serial("id").primaryKey(),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  date: date("date").notNull(),
  status: text("status").notNull(), // 'present' | 'absent' | 'week_off' | 'half_day'
  markedBy: integer("marked_by").references(() => employees.id), // admin who marked (null = system)
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (table) => [
  index("idx_attendance_employee").on(table.employeeId),
  index("idx_attendance_date").on(table.date),
  uniqueIndex("idx_attendance_employee_date").on(table.employeeId, table.date),
]);

export const insertAttendanceSchema = createInsertSchema(attendanceRecords).omit({ id: true, createdAt: true, updatedAt: true });
export type AttendanceRecord = typeof attendanceRecords.$inferSelect;
export type InsertAttendanceRecord = typeof attendanceRecords.$inferInsert;

// === CHAT MESSAGES ===
export const messages = pgTable("messages", {
  id: serial("id").primaryKey(),
  senderId: integer("sender_id").notNull().references(() => employees.id),
  recipientId: integer("recipient_id").references(() => employees.id), // null = broadcast to all admins
  content: text("content").notNull(),
  isRead: boolean("is_read").notNull().default(false),
  createdAt: timestamp("created_at").defaultNow(),
}, (table) => [
  index("idx_messages_sender").on(table.senderId),
  index("idx_messages_recipient").on(table.recipientId),
  index("idx_messages_created").on(table.createdAt),
]);

export const insertMessageSchema = createInsertSchema(messages).omit({ id: true, createdAt: true });
export type Message = typeof messages.$inferSelect;
export type InsertMessage = typeof messages.$inferInsert;

// === RELATIONS ===
export const employeeRelations = relations(employees, ({ many }) => ({
  orders: many(orders),
  issues: many(issues),
  attendance: many(attendance),
}));

export const ordersRelations = relations(orders, ({ one, many }) => ({
  employee: one(employees, { fields: [orders.employeeId], references: [employees.id] }),
  issues: many(issues),
}));

export const issuesRelations = relations(issues, ({ one }) => ({
  order: one(orders, { fields: [issues.orderId], references: [orders.id] }),
  employee: one(employees, { fields: [issues.employeeId], references: [employees.id] }),
}));

// === INSERT SCHEMAS ===
export const insertEmployeeSchema = createInsertSchema(employees).omit({ id: true, createdAt: true });
export const insertOrderSchema = createInsertSchema(orders).omit({ id: true });
export const insertIssueSchema = createInsertSchema(issues).omit({ id: true, createdAt: true });
export const insertLiveTrackingSchema = createInsertSchema(beauticianLiveTracking).omit({ id: true, timestamp: true });
export const insertServiceSessionSchema = createInsertSchema(orderServiceSessions).omit({ id: true });

// === TYPES ===
export type Employee = typeof employees.$inferSelect;
export type Order = typeof orders.$inferSelect;
export type Issue = typeof issues.$inferSelect;
export type Attendance = typeof attendance.$inferSelect;
export type LocationUpdate = typeof locationHistory.$inferSelect;
export type LiveTracking = typeof beauticianLiveTracking.$inferSelect;
export type InsertEmployee = typeof employees.$inferInsert;
export type InsertOrder = typeof orders.$inferInsert;
export type InsertIssue = typeof issues.$inferInsert;
export type InsertLiveTracking = typeof beauticianLiveTracking.$inferInsert;
export type ServiceSession = typeof orderServiceSessions.$inferSelect;
export type InsertServiceSession = typeof orderServiceSessions.$inferInsert;
export type Product = typeof products.$inferSelect;
export type InsertProduct = typeof products.$inferInsert;
export type ProductPurchase = typeof productPurchases.$inferSelect;
export type InsertProductPurchase = typeof productPurchases.$inferInsert;
export type ProductConsumption = typeof productConsumptions.$inferSelect;
export type InsertProductConsumption = typeof productConsumptions.$inferInsert;
export type ProductRequest = typeof productRequests.$inferSelect;
export type InsertProductRequest = typeof productRequests.$inferInsert;
export type ServiceProductMap = typeof serviceProductMapping.$inferSelect;
export type InsertServiceProductMap = typeof serviceProductMapping.$inferInsert;
export type ProductsNotFound = typeof productsNotFound.$inferSelect;
export type InsertProductsNotFound = typeof productsNotFound.$inferInsert;
export type OrderDefaultProduct = typeof orderDefaultProducts.$inferSelect;
export type InsertOrderDefaultProduct = typeof orderDefaultProducts.$inferInsert;

// ================================================================
// === AUTO BALANCE WALLET SYSTEM (additive — do not modify above)
// ================================================================

// UPI / QR code per employee (admin-editable, employee read-only)
export const employeeUpiProfiles = pgTable("employee_upi_profiles", {
  id: serial("id").primaryKey(),
  employeeId: integer("employee_id").notNull().unique().references(() => employees.id),
  upiNumber: text("upi_number"),
  qrCodeData: text("qr_code_data"), // base64-encoded image or URL
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// One balance record per employee (carries forward, no monthly reset)
export const autoBalances = pgTable("auto_balances", {
  id: serial("id").primaryKey(),
  employeeId: integer("employee_id").notNull().unique().references(() => employees.id),
  currentBalance: numeric("current_balance").notNull().default("0"),
  lastUpdatedAt: timestamp("last_updated_at").defaultNow(),
});

// Every balance change is logged here
export const autoBalanceLedger = pgTable("auto_balance_ledger", {
  id: serial("id").primaryKey(),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  type: text("type").notNull(), // 'top_up' | 'spend' | 'reversal' | 'adjustment'
  amount: numeric("amount").notNull(), // positive = credit, negative = debit
  balanceAfter: numeric("balance_after").notNull(),
  createdById: integer("created_by_id").references(() => employees.id),
  relatedSpendEntryId: integer("related_spend_entry_id"), // FK set after spend_entries insert
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
}, (table) => [
  index("idx_ledger_employee").on(table.employeeId),
  index("idx_ledger_created").on(table.createdAt),
]);

// Employee spend submissions (screenshot + amount)
export const spendEntries = pgTable("spend_entries", {
  id: serial("id").primaryKey(),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  amount: numeric("amount").notNull(),
  screenshotData: text("screenshot_data"), // base64 encoded (jpeg/png)
  screenshotMime: text("screenshot_mime").default("image/jpeg"),
  notes: text("notes"),
  // approved = default after submission; verified = admin confirmed; rejected = reversed
  status: text("status").notNull().default("approved"),
  reviewedById: integer("reviewed_by_id").references(() => employees.id),
  reviewedAt: timestamp("reviewed_at"),
  createdAt: timestamp("created_at").defaultNow(),
}, (table) => [
  index("idx_spend_employee").on(table.employeeId),
  index("idx_spend_created").on(table.createdAt),
  index("idx_spend_status").on(table.status),
]);

// Employee top-up requests (pending → acknowledged → fulfilled)
export const topUpRequests = pgTable("top_up_requests", {
  id: serial("id").primaryKey(),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  requestedAmount: numeric("requested_amount"), // employee's suggested amount (optional)
  status: text("status").notNull().default("pending"), // 'pending' | 'acknowledged' | 'fulfilled'
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
  acknowledgedAt: timestamp("acknowledged_at"),
  acknowledgedById: integer("acknowledged_by_id").references(() => employees.id),
  fulfilledAt: timestamp("fulfilled_at"),
  fulfilledById: integer("fulfilled_by_id").references(() => employees.id),
}, (table) => [
  index("idx_topup_employee").on(table.employeeId),
  index("idx_topup_status").on(table.status),
]);

// === AUTO BALANCE TYPES ===
export type EmployeeUpiProfile = typeof employeeUpiProfiles.$inferSelect;
export type AutoBalance = typeof autoBalances.$inferSelect;
export type AutoBalanceLedgerEntry = typeof autoBalanceLedger.$inferSelect;
export type SpendEntry = typeof spendEntries.$inferSelect;
export type TopUpRequest = typeof topUpRequests.$inferSelect;

// === PAYMENT ENTRIES ===
export const paymentEntries = pgTable("payment_entries", {
  id: serial("id").primaryKey(),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  orderId: integer("order_id").references(() => orders.id), // null for ad-hoc
  amount: numeric("amount").notNull(),
  paymentMode: text("payment_mode").notNull().default("cash"), // 'cash' | 'upi'
  screenshotData: text("screenshot_data"),
  screenshotMime: text("screenshot_mime").default("image/jpeg"),
  notes: text("notes"),
  customerName: text("customer_name"), // for ad-hoc only
  isAdhoc: integer("is_adhoc").notNull().default(0), // 0=order-linked, 1=ad-hoc
  status: text("status").notNull().default("approved"), // 'approved' | 'pending_approval' | 'rejected'
  reviewedById: integer("reviewed_by_id").references(() => employees.id),
  reviewedAt: timestamp("reviewed_at"),
  createdAt: timestamp("created_at").defaultNow(),
}, (table) => [
  index("idx_pe_employee").on(table.employeeId),
  index("idx_pe_status").on(table.status),
  index("idx_pe_created").on(table.createdAt),
]);
export type PaymentEntry = typeof paymentEntries.$inferSelect;
